development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://radar-faye.herokuapp.com/faye"
  secret_token: "5ccb1c71dacfe644ebfdad99d4691e0516e1e186335c7e98cda2ef999032b766"
  signature_expiration: 3600 # one hour
